### ISSUE TITLE
Similar goals feature (2 options)

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#13]
- people have similar goals, how can people just put that in
      - choose past tasks/goals
- goal, choose timespan

**Comment by kailicen** [comment]
put in short term and long term goals, they will appear across different weeks based on the time span

![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/b18c74d4-bf23-4602-b665-4cccbb88d352)

@setthawut8 Please test this feature!

**Comment by setthawut8** [comment]
It works well! I have tried it and users would be happy. No need to write each week. Btw, really like the new color sets.
