### ISSUE TITLE
Get all users' emails from two web apps and send them email that we are switching back to the previous version.

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#14]
- Get all users' emails from the old web app (I can get it from firebase, we have 105)
- Get all users' emails from the new one, Boom, is it easy for you to get them from the posthog or the data tool we are using?

**Comment by kailicen** [comment]
@setthawut8

**Comment by kailicen** [comment]
Have export all users' emails from both firebase and posthog. and putting them in Benchmark email.

**Comment by setthawut8** [comment]
Just saw it. Thanks Kaili
