### ISSUE TITLE
Reward system: badges, leaderboard

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#31]
Boom: 
- badges: based on "have they done what they said they will do?" 
- measurement: add task completion rate 
- week 1 badge, week 2, 3, ... 
- [FYI] Potential UX/UI ideas for the leaderboard to use as a foundation for further enhancements, 
[@Kaili](https://kaikul.slack.com/team/U05C9B7RM97)
.
https://dribbble.com/shots/17641777-Sherbet-UI-s
https://www.behance.net/gallery/178808037/Daily-UI-Challenge-Leaderboard-019?tracking_source=search_projects%7CLeaderboard
https://www.behance.net/gallery/163933453/Day-19-of-DailyUI-Leaderboard?tracking_source=search_projects%7CLeaderboard

Kaili: 
- where to put it, data structure.

**Comment by kailicen** [comment]
Badges:

- Act (Streaks): can do 80-90% of total jobs continuously for each time period. each badge will be vary based on current performance

- Objectives: make people motivated to sustain their habits.

Rhodium: 4 weeks
Gold: 3 weeks
Silver: 2 weeks
Bronze: 1 week

- Reflector: at least reflect one time continuously for each time period

- Objectives: make people motivated to reflect where they are and what keep doing and what need to improve.

Rhodium: 4 weeks
Gold: 3 weeks
Silver: 2 weeks
Bronze: 1 week

- [Need to Discuss] Features:

- Forum

1. Following & Follower with comment and like
2. For what? make users more interactive.
3. users can follow interesting one(s) to see each reflection or calendar. Also, comment and like
4. Email Notification for Weekly Results.
5. For what? reminder them about their performance
6. Send stats page to them on email.

**Comment by kailicen** [comment]
- point system
- my stats
- badges

**Comment by kailicen** [comment]
https://kaikul-app-git-features-reward-badges-le-b6c255-kailicen-s-team.vercel.app/

If you guys have time, please test this @setthawut8 @arniemutasa @CodeNKoffee

**Comment by kailicen** [comment]
sorry @setthawut8 your idea is a bit hard to implement, so I use the point system to get it done first.

**Comment by setthawut8** [comment]
After testing, overall is really good, especially 'My Journal' Page'. No need to switch between pages, just one good page. A lot more efficient.

The main function is perfect. If you ask me what can enhance? just tiny two things

1) Not too close, more spaces for a tooltip (an image attached)

![Image](https://github.com/KaiKulApp/kaikul-app/assets/75829649/3eacaf5e-d72d-4588-a787-34f7cd54880c)


2) Feel a bit too much spaces on  "Catalyst Tools For My Journey" (no need to fix it now, low priority)
