### ISSUE TITLE
Adjust Accountability Content on Landing Page

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#32]
Why? currently, we are not matching people, there's no such feature. our current approach is engaging users use the share to Slack feature. 

Wait, is this what we want? I need to think about the sharing feature.

**Comment by kailicen** [comment]
**One-Liner**: KaiKul: Where Ownership Meets Purpose.
**Short Description**: KaiKul is a personal development platform designed to foster conscious living and nurture personal responsibility.
**Explanation**: 
- Intro: In the rush of daily life, many individuals lose sight of their long-term aspirations. The constant pressure to do more often overshadows the essential need to pause, reflect, and recalibrate. This is where KaiKul steps in, a beacon guiding you back to a path of purpose and conscious living.
- The Concept of Ownership: Ownership isn't just about responsibility; it is about embracing your unique journey and honoring your commitments to yourself. When you take ownership of your life, every step, every task becomes a conscious choice steering you towards the long-term goals that resonate with your inner self.
- Our Unique Framework: At the heart of KaiKul is our innovative goal-task-reflection framework:
1. Goal: Start with a clear, long-term goal that defines what you truly aspire to achieve, breaking free from the short-sighted vision that often clouds modern life.
2. Task: Next, break down your overarching goal into manageable, daily tasks, maintaining a focus that is both detailed and grounded.
3. Reflection: The reflection stage fosters growth through conscious living, allowing you to learn from each day and to adapt and evolve dynamically.
- The Role of Reflection: Reflection is not a passive process. It is an active engagement with your journey, a way to nurture awareness and foster growth from a place of understanding and acceptance. It allows you to correct your course timely, embracing the iterative process of personal growth.
- Conclusion: With KaiKul, you're not just working towards a goal. You're nurturing an increased awareness, fostering a greater understanding of yourself, and stepping into a fuller, richer life. Through consistency and conscious living, we facilitate not just achievement, but personal evolution and growth.

**Comment by kailicen** [comment]
@setthawut8 Please review new landing page, and share your thoughts!

**Comment by setthawut8** [comment]
Woww, well done Kaili! That's the word, "ownership". Sound a lot lot...better than accountability. If you ask me what to enhance, nothing. It now works best. 🔥

**Comment by kailicen** [comment]
- how it work page bug, mobile screen can't see. change bg to light (potentially because Chakra UI overwrite tailwind)
- use other perspectives to write the landing page.
