### ISSUE TITLE
sendgrid email, when user first sign in they got an welcome email

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#34]

**Comment by kailicen** [comment]
Finally finished the email: 

🌱 Welcome to KaiKul - Your Journey to Purposeful Living Starts Here!

Hi [User’s Name],

Welcome to the KaiKul family – where ownership meets purpose!

I'm Kaili, the heart behind KaiKul. Inspired by personal struggles to stay committed to my goals, I created this platform to help individuals like you and me not just set intentions, but truly live them, every single day.

Here's how we do it:

1. **Goal**: Define what matters most to you.
2. **Task**: Break it down into achievable tasks.
3. **Reflection**: Reflect, learn, and grow from each experience.

**Community**: Connect with like-minded individuals on our [Slack community](https://join.slack.com/t/kaikul/shared_invite/zt-22ty7x0ps-89ruM2VXwB1v49yY35cYdw).
**Guide**: Check out our [how-to guide](https://www.canva.com/design/DAFuQHGqA1Y/rIa9fyabkD0dnyBQh4ynKg/view) to bootstrap your KaiKul journey.

Ready to take the leap? [Sign up for our web app](https://kaikul.com) to embrace a life where your ownership meets purpose.

Here’s to living consciously and fulfilling promises to yourself, one small step at a time.

See you inside,

KaiKul Team

**Comment by CodeNKoffee** [comment]
Splendid work, Kaili!

**Comment by kailicen** [comment]
Hi Arnold, can you check mailtrap? The function is working, but the email is not sending. Happy to have a short call for it. 

I use this script to test, not working. 

const nodemailer = require("nodemailer");

const mailTransport = nodemailer.createTransport({
  host: "sandbox.smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "705798b37178be",
    pass: "09f34148192697",
  },
});

const mailOptions = {
  from: "Kaikul : no-reply@kaikul.com",
  to: "kailicen226@gmail.com", // replace with your own email address for testing
  subject: "Welcome to Kaikul",
  html: "<p>Test email from Kaikul</p>",
};

async function sendTestEmail() {
  try {
    await mailTransport.sendMail(mailOptions);
    console.log("Welcome Mail Sent");
  } catch (error) {
    console.error("There was an error while sending the email:", error.message);
  }
}

sendTestEmail();
