### ISSUE TITLE
Data analytics

### ISSUE THREAD

**Issue by kailicen** [KaiKulApp/kaikul-app#35]
Hi Setthawut,

Yes you should be able to embed our [JavaScript SDK](https://t.sidekickopen53.com/Ctc/U+23284/cRblz04/Jks2-6qcW69sMD-6lZ3njW8QP6nf8p1m4rW3-9LBZ8nghm3W59_jQf3Zxb-nW23xxBj359BG3W4pSzQC8l6q5gW5SZJbv79vcmRW62frQv71n-2sW2_fw3L2llQfZW2VxjWV7Xb7B5W8N8-ck10rl1JW4CnKH18l6btBW7QCCXW32pT_KW1K2DnC9783MPTT0GX1sPtc-N4fbc6r6VTz5W3hsbFd7lCyf3W2GTPCX4JjGXmVLCCLh6g2dwVN7VpHZGSnym2Vq0lWL3sDWCPf8vTr9T04) and track events which will let you then visualize the metrics you need in our platform.

Thanks,

Simon Fisher

**Comment by setthawut8** [comment]
**How To Links**
- Firebase to Power BI [link](https://www.nitorinfotech.com/blog/integrate-firebase-with-power-bi-using-big-query/)
- Firebase to Google Data Studio [link](https://hevodata.com/learn/firebase-data-studio-integration-2-easy-methods/)
- Firebase to Posthog [link](https://posthog.com/docs/libraries/js)

**Comment by kailicen** [comment]
What data do we need? 
- userPoints - metrics
- boom's metrics

**Comment by setthawut8** [comment]
What data do we need?

**Marketing Funnel**
- _Click-Through Rate_: how many people click a link while getting a message?
- _Conversion Rate_: how many people visit our landing page and sign up out of total visitors?

**People Engagement & Understanding**
- userPoints - metrics
- _Retention Rate_: how many people return to use KaiKul in 7 days, 14 days, 21 days and a month out of total users?
- _Most Viewed Pages_: what page is the most popular for them?
- _Geographic data_: Which country are users from?

@kailicen @CodeNKoffee @arniemutasa. This is data for now we needed to gain people insights.
