### ISSUE TITLE
Light/Dark Mode Color Conflicts

### ISSUE THREAD

**Issue by CodeNKoffee** [KaiKulApp/kaikul-app#44]

**Comment by kailicen** [comment]
Sorry @CodeNKoffee I merge too quickly, now I am testing it. There are a few things can be improved: 
1. Nav bar also can be dark, the white stands out too weirdly. 


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/0c7c191f-407a-4222-b133-def07a57fbf3)

2. Some text can't be seen, hover chart text, text in tasks. Either the bg color goes darker or the text goes darker. 


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/d14a547c-2ca3-4524-926f-f6e0ce494deb)


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/2a7c88eb-1e16-45f1-b3e5-55656c08b45b)

3. KaiKul purple color is too dark to see in dark mode, needs a lighter purple to contrast. 


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/d9f7dc9a-8ac2-450b-a340-837743fad8fe)


4. The outline of the box is too white, can be lighter


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/e862a072-16b8-4efd-b8e2-3eca19098e84)

**Comment by kailicen** [comment]
@CodeNKoffee I've done nav bar and "Self Discover" page



![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/51a2331a-639c-4095-8281-a95c1a73b0f3)

In chakra ui, needs to use something like this: 


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/1a55a0bb-a367-4a5c-a567-c9aa596a8c69)


![Image](https://github.com/KaiKulApp/kaikul-app/assets/39973875/1b844d8e-f9bd-4a15-a149-aeceedc8e400)

**Comment by CodeNKoffee** [comment]
Got it! I will start working on the above points (from what has NOT been done) and I will make sure to double-check. GOOD EYE 👁️ 

Thanks, @kailicen  for the note! Also, didn't notice you tagged me for the navigation bar part...

Let's keep it going !🔥 💪
